
version: '3.1'

services:

  auth-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: auth
    ports:
      - "3306:3306"
    volumes:
      - "./src/test/resources/db/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql"